name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      containers:
        description: 'Shard containers to use'
        required: false
        default: '[1, 2]'
        type: string

env:
  PLAYWRIGHT_BROWSERS_PATH: ms-playwright-cache
  NODE_VERSION: 22.x

jobs:
  testing:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        containers: ${{ fromJSON(inputs.containers || '[1, 2]') }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: useblacksmith/setup-node@65c6ca86fdeb0ab3d85e78f57e4f6a7e4780b391 # v5.0.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.0.0
        with:
          run_install: |
            args: [--frozen-lockfile]

      - name: Configure Turborepo Cache
        uses: useblacksmith/caching-for-turbo@bafb57e7ebdbf1185762286ec94d24648cd3938a # v1

      - name: Build for Playwright
        run: pnpm turbo build:playwright

      - name: Start local server
        run: |
          E2E_TESTS=true pnpm start &
          npx wait-on http://localhost:5678 --timeout 15000

      - name: Run Playwright tests (shard ${{ matrix.containers }}/${{ strategy.job-total }})
        working-directory: playwright
        run: pnpm exec playwright test --shard=${{ matrix.containers }}/${{ strategy.job-total }} --workers=4
        env:
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: results-${{ matrix.containers }}.xml
          CI: true
          TEST_SHARD_INDEX: ${{ matrix.containers }}
          N8N_BASE_URL: http://localhost:5678
          RESET_E2E_DB: true

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-results-${{ matrix.containers }}
          path: playwright/blob-report/
          retention-days: 3

  merge-reports:
    if: ${{ failure() }}
    needs: [testing]
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Setup Node.js
        uses: useblacksmith/setup-node@65c6ca86fdeb0ab3d85e78f57e4f6a7e4780b391 # v5.0.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download all test results
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: playwright-results-*
          path: all-reports/

      - name: Merge test reports
        run: |
          npx -y @playwright/test merge-reports \
            --reporter=html,github \
            all-reports/playwright-results-*/blob-report

      - name: Upload merged report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-report-merged
          path: playwright-report/
          retention-days: 3
